language: node_js
node_js:
- '8'
script:
- yarn install
- yarn test
- yarn build
deploy:
  provider: firebase
  token:
    secure: cZw91wu/I7Q6M44bksYNoe15U5g9Stdr0foBCriE/scE6mIpZd/j0ZlI4ugcalD8IFdXuVZ9FJ5xzItlRkJ0oUOiBM/Km7WIldGR7dlNMe6/L7DpHtSn+uyRW96oOZEue74DYoslG9E1dSfOVdwFjV9ZmhLa1H1dli6VERPdGPeMxvujpI+TNwWaMjkCgneGuu/$
  project: project-5789381722182983929
  message: 'Deployed to firebase: https://project-5789381722182983929.firebaseapp.com/'
