language: node_js
node_js:
- '12'
script:
- npm install
- npm test
- npm build
deploy:
  provider: firebase
  project: project-5789381722182983929
  message: 'Deployed to firebase: https://project-5789381722182983929.firebaseapp.com/'
  skip_cleanup: true
  token:
    secure: BDbDJCwUuXY/at+J1Y+Bqv9JC5gfinky3EANiq29VdTAsX7t9YAxXJGpRcZ+RdODS62w4uLugtzJTLGWwdT3pDDyI5UfCSnbGTw1hSUwpbAInFwzDlwimJQNBZ4mEQSGrKgog/ADsPYhY7eHNsH4kI1tYYkI0eVULz2mcPesU6OmRSJwttmaqAEAfmAqwiebwm6/7LKT5r3yOiOlXuyr0mla/fXdDkBA4u7ZcEAE9sbuqbtZN0tHM0LreJVH0EI9OyNMrtZXK3HJ8uWYvBabekZgin8x04uipYNm+QiYWRi6BtLOjvIXw8TlHdDv831TpVvyNoLQixeSC30AvH7Kod4+KAK8yzfc+P8O2Vo5/6WfcstghOPXQ8EUg4i1o04yn3DVn/EucENshHfMgr2gizk4xaFGac4EiLWzTwcQVHM25sfn69NF9CUz/TGmV0sUlm6FtEIuVbBzemyUQSMgXFdnPsHeSbPwpyWWSPEkLyZGBX6G+eWgWOR7vJT++MJc23FEdSWIBUtWxbq03OeYuABarTBDQixpfG+NzVAwbkkge7G6IcoINlZGlTgej/hlk4WtUtaWJF1gusNLudh0vcDi7LLQYQh6dPNVZQdUa2DzhQ0B+Mwk1E8f+3uUehxzeH7KJlmO7A2ZrrOqryg8NrIegefOIZc5VxhmYX2MQg8=
